### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by strukturart** [strukturart/o.map#47]
- [ ] LMK warnig KaiOS V3
- [ ] Navigation from current location
- [ ] trigger marks tracking UI e.g. after 5km, 500m alitude, > 80kmh.....
